<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BaseApi.Tests</RootNamespace>
    <AssemblyName>BaseApi.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <None Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.v3.assert" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BaseApi.Core\BaseApi.Core.csproj" />
    <ProjectReference Include="..\..\BaseApi.Service\BaseApi.Service.csproj" />
    <ProjectReference Include="..\..\BaseConsole.Core\BaseConsole.Core.csproj" />
    <ProjectReference Include="..\..\Messaging.Transport\Messaging.Transport.csproj" />
    <ProjectReference Include="..\..\BaseProcessor.Core\BaseProcessor.Core.csproj" />
    <ProjectReference Include="..\..\Processor.Sample\Processor.Sample.csproj" />
    <ProjectReference Include="..\..\Orchestrator\Orchestrator.csproj" />
  </ItemGroup>

</Project>
