using Microsoft.Extensions.Options;
using Processor.SKNormalizer;
using Xunit;

namespace BaseApi.Tests.SKNormalizer;

public sealed class FfmpegAudioTranscoderTests
{
    private static FfmpegAudioTranscoder Build(string path, int timeoutSeconds = 300)
        => new(Options.Create(new SKNormalizerOptions
        {
            FfmpegPath = path,
            ConversionTimeoutSeconds = timeoutSeconds,
        }));

    [Fact]
    public void AnAbsentBinaryIsABusinessFailureNotACrash()
    {
        // THE FIRST THING TO GO WRONG ON A FIRST DEPLOY. A missing binary must not surface as a
        // Win32Exception escaping the processor — it reads as a content problem when it is an image
        // problem, and the message is what tells them apart.
        var transcoder = Build("definitely-not-a-real-binary-9f3a");

        var ex = Assert.Throws<NormalizationException>(
            () => transcoder.Transcode(
                [1, 2, 3], ".wav", new AudioProfile(".mp3", []), CancellationToken.None));

        Assert.Contains("definitely-not-a-real-binary-9f3a", ex.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void ACancelledTokenStopsBeforeAnythingIsSpawned()
    {
        using var cts = new CancellationTokenSource();
        cts.Cancel();

        Assert.Throws<OperationCanceledException>(
            () => Build("ffmpeg").Transcode(
                [1, 2, 3], ".wav", new AudioProfile(".mp3", []), cts.Token));
    }

    [Trait("Category", "RealStack")]
    [Fact]
    public void ARealConversionProducesBytesAndAProbedDuration()
    {
        // NEEDS THE BINARY, so it is RealStack and not part of the hermetic suite. The source is
        // generated by ffmpeg itself rather than checked in, so this test carries no binary asset.
        var source = Build("ffmpeg").Transcode(
            [],
            ".null",
            new AudioProfile(".wav", ["-f", "lavfi", "-i", "sine=frequency=440:duration=1"]),
            CancellationToken.None);

        Assert.NotEmpty(source.Content);
        Assert.Equal(".wav", source.Extension);
        Assert.Equal(source.Content.LongLength, source.SizeBytes);
    }
}
