using System.Diagnostics;
using Microsoft.Extensions.Options;
using Processor.SKNormalizer;
using Xunit;

namespace BaseApi.Tests.SKNormalizer;

public sealed class FfmpegAudioTranscoderTests
{
    private static FfmpegAudioTranscoder Build(string path, int timeoutSeconds = 300)
        => new(Options.Create(new SKNormalizerOptions
        {
            FfmpegPath = path,
            ConversionTimeoutSeconds = timeoutSeconds,
        }));

    [Fact]
    public void AnAbsentBinaryIsABusinessFailureNotACrash()
    {
        // THE FIRST THING TO GO WRONG ON A FIRST DEPLOY. A missing binary must not surface as a
        // Win32Exception escaping the processor — it reads as a content problem when it is an image
        // problem, and the message is what tells them apart.
        var transcoder = Build("definitely-not-a-real-binary-9f3a");

        var ex = Assert.Throws<NormalizationException>(
            () => transcoder.Transcode(
                [1, 2, 3], ".wav", new AudioProfile(".mp3", []), CancellationToken.None));

        Assert.Contains("definitely-not-a-real-binary-9f3a", ex.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void ACancelledTokenStopsBeforeAnythingIsSpawned()
    {
        using var cts = new CancellationTokenSource();
        cts.Cancel();

        Assert.Throws<OperationCanceledException>(
            () => Build("ffmpeg").Transcode(
                [1, 2, 3], ".wav", new AudioProfile(".mp3", []), cts.Token));
    }

    [Trait("Category", "RealStack")]
    [Fact]
    public void ARealConversionProducesBytesAndAProbedDuration()
    {
        // NEEDS THE BINARY, so it is RealStack and not part of the hermetic suite. The source is
        // generated by ffmpeg itself rather than checked in, so this test carries no binary asset.
        var source = Build("ffmpeg").Transcode(
            [],
            ".null",
            new AudioProfile(".wav", ["-f", "lavfi", "-i", "sine=frequency=440:duration=1"]),
            CancellationToken.None);

        Assert.NotEmpty(source.Content);
        Assert.Equal(".wav", source.Extension);
        Assert.Equal(source.Content.LongLength, source.SizeBytes);
    }

    [Trait("Category", "RealStack")]
    [Fact]
    public void ARealConversionProbesTheOUTPUTCodecAndBitrateRatherThanTheInputs()
    {
        // NEEDS THE BINARY. THE REGRESSION THIS EXISTS FOR: ffmpeg prints the input's stream line
        // before the output's, so an unscoped first-match over stderr reported the SOURCE -- a wav
        // transcoded to 192k mp3 probed as pcm_s16le at 1411 kb/s, and AcmeHandler.Reconcile wrote
        // both into the metadata beside a file that is now mp3.
        var transcoder = Build("ffmpeg");

        var wav = transcoder.Transcode(
            [],
            ".null",
            new AudioProfile(".wav", ["-f", "lavfi", "-i", "sine=frequency=440:duration=2"]),
            CancellationToken.None);

        var mp3 = transcoder.Transcode(
            wav.Content, ".wav",
            new AudioProfile(".mp3", ["-c:a", "libmp3lame", "-b:a", "192k"]),
            CancellationToken.None);

        Assert.Equal("mp3", mp3.Codec);
        Assert.Equal(192, mp3.BitrateKbps);

        // Duration comes from the INPUT block and that is correct -- a transcode does not change
        // how long the audio is. Asserted so the fix above cannot be "scope everything".
        Assert.Equal(2, mp3.Duration?.TotalSeconds ?? 0, 1);
    }

    [Trait("Category", "RealStack")]
    [Fact]
    public void ACancellationAfterStartKillsTheChildInsteadOfWaitingItOut()
    {
        // NEEDS THE BINARY. "-re" paces ffmpeg at real time so the 30s duration is genuinely
        // long-running rather than finishing instantly — a cancellation that is ignored would
        // otherwise be indistinguishable from a fast conversion.
        using var cts = new CancellationTokenSource();
        cts.CancelAfter(TimeSpan.FromSeconds(1));

        var stopwatch = Stopwatch.StartNew();

        Assert.Throws<OperationCanceledException>(
            () => Build("ffmpeg").Transcode(
                [],
                ".null",
                new AudioProfile(".wav", ["-re", "-f", "lavfi", "-i", "sine=frequency=440:duration=30"]),
                cts.Token));

        stopwatch.Stop();

        // Bounded well under the 30s the conversion would take uncancelled — proves the child was
        // killed rather than run to completion or to the (much larger) default timeout.
        Assert.True(
            stopwatch.Elapsed < TimeSpan.FromSeconds(15),
            $"expected cancellation to return quickly, took {stopwatch.Elapsed}");
    }

    [Trait("Category", "RealStack")]
    [Fact]
    public void ATimeoutIsReportedAsABusinessFailureNamingTheLimit()
    {
        // NEEDS THE BINARY. Same long-running profile as the cancellation test, but here the token
        // is never cancelled — the timeout is what stops it.
        var ex = Assert.Throws<NormalizationException>(
            () => Build("ffmpeg", timeoutSeconds: 1).Transcode(
                [],
                ".null",
                new AudioProfile(".wav", ["-re", "-f", "lavfi", "-i", "sine=frequency=440:duration=30"]),
                CancellationToken.None));

        Assert.Contains("within 1s", ex.Message, StringComparison.Ordinal);
    }
}
