<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="JsonSchema.Net" />
    <PackageReference Include="OpenTelemetry" />
    <ProjectReference Include="..\BaseConsole.Core\BaseConsole.Core.csproj" />
    <ProjectReference Include="..\Messaging.Contracts\Messaging.Contracts.csproj" />
    <ProjectReference Include="..\Messaging.Transport\Messaging.Transport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BaseApi.Tests" />
  </ItemGroup>

</Project>
